# Generated by Django 5.1.3 on 2024-11-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentorder',
            name='contact',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='currentorder',
            name='contactType',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='currentorder',
            name='items',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='currentorder',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='currentorder',
            name='orderTime',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='currentorder',
            name='orderType',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='currentorder',
            name='queuePosition',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='currentorder',
            name='tip',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='currentorder',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pastorder',
            name='items',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='pastorder',
            name='orderTime',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pastorder',
            name='orderType',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='pastorder',
            name='tip',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pastorder',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
