# Generated by Django 5.1.3 on 2024-11-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_currentorder_contact_currentorder_contacttype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentorder',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='currentorder',
            name='contactType',
        ),
        migrations.AddField(
            model_name='currentorder',
            name='currentTime',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='currentorder',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='currentorder',
            name='queuePosition',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
