# Generated by Django 5.1.3 on 2024-12-07 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_currentorder_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('partySize', models.IntegerField(default=1)),
                ('reservationDateTime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='PastReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partySize', models.IntegerField(default=1)),
                ('reservationDateTime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
