# Generated by Django 5.1.4 on 2024-12-07 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_currentreservation_pastreservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PastReservation',
        ),
        migrations.RemoveField(
            model_name='currentorder',
            name='currentTime',
        ),
    ]
